
# This is a Kubernetes Deployment manifest.
# A Deployment is a Kubernetes object that manages a set of identical Pods.
# It ensures that a specified number of Pods are running and handles updates and rollbacks.

apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of the Deployment object itself.
  name: taskmanager-app-deployment
spec:
  # `replicas` defines the desired number of running application instances (Pods).
  replicas: 1

  # The `selector` tells the Deployment which Pods to manage.
  # It finds Pods by matching their labels.
  selector:
    matchLabels:
      app: taskmanager-app

  # The `template` is the blueprint for the Pods that the Deployment will create.
  template:
    metadata:
      # These labels are applied to each Pod created from this template.
      # The `selector` above must match these labels.
      labels:
        app: taskmanager-app
    spec:
      # Add this section to specify the secret to use for pulling the image from the private registry.
      imagePullSecrets:
        - name: acr-secret
      # A Pod can contain one or more containers. We have one for our application.
      containers:
        - name: taskmanager-app-container
          # IMPORTANT: This is the Docker image that will be run.
          # Our CI/CD pipeline will dynamically replace this placeholder
          # with the actual image URL and tag from our Azure Container Registry (e.g., myacr.azurecr.io/taskmanager-app:commit-sha)
          image: YOUR_ACR_LOGIN_SERVER/taskmanager-app:latest

          # The port inside the container that the application listens on.
          ports:
            - containerPort: 8080

          # Environment variables that will be injected into the running container.
          # We use these to pass database connection details to the Spring Boot application.
          env:
            # Activate the 'docker' profile to use PostgreSQL settings
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            # The full JDBC URL for the database connection, fetched directly from the secret.
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-url

            # The database username, fetched from the same Secret.
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-user

            # The database password, also fetched from the same Secret.
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
