name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to upload packages to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@v0.10.0
        with:
          # The image name in GHCR. It's recommended to use lowercase.
          # ${{ github.repository }} resolves to "owner/repository-name"
          image: ghcr.io/${{ github.repository }}
          dockerfile: ./Dockerfile.app
          # Build and push with two tags: the commit SHA and "latest"
          tags: |
            ${{ github.sha }}
            latest
