name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to upload packages to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with Kaniko
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /home/runner/.docker/config.json:/kaniko/.docker/config.json \
            gcr.io/kaniko-project/executor:v1.12.1 \
            --context=/workspace \
            --dockerfile=/workspace/Dockerfile.app \
            --destination=ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --destination=ghcr.io/${{ github.repository }}:latest
